steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: ${{ parameters.pythonVersion }}
    addToPath: true
    architecture: x64
- script: |
    python3 -m pip install mypy
    python3 -m pip install types-certifi types-pkg_resources types-python-dateutil types-requests types-attrs
    # These PyQt6 stubs are not updated often enough. Even the versions at the tip at the time of
    # this commit are not good enough and have gaps.
    pip install git+https://github.com/python-qt-tools/PyQt6-stubs.git@f623a641cd5cdff53342177e4fbbf9cae8172336
    python3 -m mypy --config-file mypy.ini --python-version ${{ parameters.pythonVersion }}
  displayName: 'Mypy static analysis'
